server:
  port: 8501
feign:
  httpclient:
    enabled: true #支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径最大连接数
    connection-timeout: 10000 # 请求时长
spring:
  rabbitmq:
    host: 192.168.14.128 #主机名
    port: 5672
    username: guapixu
    password: 123456
    virtual-host: / #虚拟主机
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完后获取下一条