server:
  port: 10010 #网关端口
spring:
  application:
    name: guapixu-project-gateway #服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos地址
    gateway:
      routes:
        - id: guapixu-project-user #路由标记，唯一
          uri: lb://guapixu-project-user #路由目标地址
          predicates: #路由断言  路径匹配规则
            - Path=/user/** #以/user开头
        - id: guapixu-project-mail #路由标记，唯一
          uri: lb://guapixu-project-mail #路由目标地址
          predicates: #路由断言  路径匹配规则
            - Path=/mail/** #以/mail开头
      default-filters:
        - StripPrefix=1
