server:
  port: 8500
feign:
  httpclient:
    enabled: true #支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径最大连接数
    connection-timeout: 10000 # 请求时长
spring:
  rabbitmq:
    host: 192.168.14.128 #主机名
    port: 5672
    username: guapixu
    password: 123456
    virtual-host: / #虚拟主机
  redis:
    host: 192.168.14.128 #redis所在主机
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8 #最大连接
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
        max-wait: 100 #连接等待时间